Models/Whitelist.cs
namespace TMDT.Models
{
	public class Whitelist
	{
		public int Id { get; set; }
		public int ProductId { get; set; }
		public string? Name { get; set; }
		public int Number {  get; set; }
        public string? Size { get; set; }
        public string? Color { get; set; }
        public string? ImagePath { get; set; }
		public DateTime? TimeOrder { get; set; }
		public float TotalPrice { get; set; }
	}
}

Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TMDT.Data;
using TMDT.Models;

namespace TMDT.Controllers
{
    public class ProductsController : Controller
    {
        private readonly TMDTDbContext _context;

        public ProductsController(TMDTDbContext context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            return View(await _context.Products.ToListAsync());
        }

        [HttpGet]
        public IActionResult GetData(string query)
        {
            if (string.IsNullOrWhiteSpace(query))
            {
                return BadRequest("Query cannot be empty");
            }

            var products = _context.Products
                .Where(p => p.Name.Contains(query))
                .Select(p => new { p.Id, p.Name })
                .ToList();

            return Json(products);
        }

        // GET: Products/Details/5
        public IActionResult Details(int Id)
        {
            var product = _context.Products.FirstOrDefault(p => p.Id == Id);

            if (product == null)
            {
                Console.WriteLine(Id);
                return NotFound(); // Xử lý khi không tìm thấy sản phẩm với ID tương ứng
            }

            return View(product); // Trả về View với sản phẩm tương ứng
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            return View();
        }


        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id, ProductId, Name, Description, ImagePath, Price, Number, decrease, CategoryId,size,color")] Products products)
        {
            if (ModelState.IsValid)
            {
                _context.Add(products);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(products);
        }

        /*public IActionResult InformationSP(int ProductId)
        {
            var product = _context.Products.FirstOrDefault(p => p.ProductId == ProductId);

            if (product == null)
            {
                return NotFound(); // Xử lý khi không tìm thấy sản phẩm với ID tương ứng
            }

            return RedirectToAction(nameof(Details)); // Trả về View với sản phẩm tương ứng
        }*/

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var products = await _context.Products.FindAsync(id);
            if (products == null)
            {
                return NotFound();
            }
            return View(products);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id, ProductId, Name,Description,ImagePath,Price,Number,decrease, CategoryId,size,color")] Products products)
        {
            if (id != products.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(products);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductsExists(products.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(products);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var products = await _context.Products
                .FirstOrDefaultAsync(m => m.Id == id);
            if (products == null)
            {
                return NotFound();
            }

            return View(products);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var products = await _context.Products.FindAsync(id);
            if (products != null)
            {
                _context.Products.Remove(products);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductsExists(int id)
        {
            return _context.Products.Any(e => e.Id == id);
        }
		
		

	}
}

Controllers/WhitelistsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TMDT.Data;
using TMDT.Models;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace TMDT.Controllers
{
    public class WhitelistsController : Controller
    {
        private readonly TMDTDbContext _context;

        public WhitelistsController(TMDTDbContext context)
        {
            _context = context;
        }

        // GET: Whilelists
        public async Task<IActionResult> Index()
        {
            return View(await _context.Whilelist.ToListAsync());
        }

        // GET: Whilelists/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var whilelist = await _context.Whilelist
                .FirstOrDefaultAsync(m => m.Id == id);
            if (whilelist == null)
            {
                return NotFound();
            }

            return View(whilelist);
        }

        // GET: Whilelists/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Whilelists/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ProductId,Name, Number,size,color,ImagePath,TimeOrder,TotalPrice")] Whitelist whilelist)
        {
            if (ModelState.IsValid)
            {
                _context.Add(whilelist);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(whilelist);
        }

        [HttpGet]
        public IActionResult Addtofavorist(int Id)
        {
            try
            {
                DateTime dateTime = DateTime.Now;

                var product = _context.Products.FirstOrDefault(q => q.Id == Id);
                var cart = _context.Whilelist.ToList();
                if (product != null)
                {

                    var existingCartItem = cart.FirstOrDefault(c => c.ProductId == Id);
                    if (existingCartItem != null)
                    {
                        return Json(new { success = false, message = "Sản phẩm đã co trong Favorist" });
                    }

                    var carts = new Whitelist()
                    {
                        ProductId = product.Id,
                        Name = product.Name,
                        Number = product.Number,
                        TotalPrice = product.Price,
                        TimeOrder = dateTime,
                        ImagePath = product.ImagePath,
                    };

                    _context.Whilelist.Add(carts);

                    _context.SaveChanges();

                    return Json(new { success = true, message = "Sản phẩm đã được thêm vào Favorist" });
                }
                else
                {
                    return NotFound();
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                return StatusCode(500, "Đã xảy ra lỗi khi thêm sản phẩm vào giỏ hàng."); // Trả về mã lỗi 500 và thông báo lỗi
            }
        }

        // GET: Whilelists/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var whilelist = await _context.Whilelist.FindAsync(id);
            if (whilelist == null)
            {
                return NotFound();
            }
            return View(whilelist);
        }

        // POST: Whilelists/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProductId,Name,size,color, Number, ImagePath,TimeOrder,TotalPrice")] Whitelist whilelist)
        {
            if (id != whilelist.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(whilelist);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WhilelistExists(whilelist.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(whilelist);
        }
        public IActionResult DeleteFavourist(int id)
        {
            var whilelist = _context.Whilelist.Find(id);
            if (whilelist != null)
            {
                _context.Whilelist.Remove(whilelist);
            }

            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        // GET: Whilelists/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var whilelist = await _context.Whilelist
                .FirstOrDefaultAsync(m => m.Id == id);
            if (whilelist == null)
            {
                return NotFound();
            }

            return View(whilelist);
        }

        // POST: Whilelists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var whilelist = await _context.Whilelist.FindAsync(id);
            if (whilelist != null)
            {
                _context.Whilelist.Remove(whilelist);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WhilelistExists(int id)
        {
            return _context.Whilelist.Any(e => e.Id == id);
        }
    }
}

Views/Whitelists/Create.cshtml
@model TMDT.Models.Whitelist

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Whilelist</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <input asp-for="ProductId" class="form-control" />
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                <input asp-for="ImagePath" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TimeOrder" class="control-label"></label>
                <input asp-for="TimeOrder" class="form-control" />
                <span asp-validation-for="TimeOrder" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalPrice" class="control-label"></label>
                <input asp-for="TotalPrice" class="form-control" />
                <span asp-validation-for="TotalPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Whitelists/Delete.cshtml
@model TMDT.Models.Whitelist

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Whilelist</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeOrder)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeOrder)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Whitelists/Details.cshtml
@model TMDT.Models.Whitelist

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Whilelist</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeOrder)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeOrder)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Whitelists/Edit.cshtml
@model TMDT.Models.Whitelist

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Whilelist</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <input asp-for="ProductId" class="form-control" />
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                <input asp-for="ImagePath" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TimeOrder" class="control-label"></label>
                <input asp-for="TimeOrder" class="form-control" />
                <span asp-validation-for="TimeOrder" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalPrice" class="control-label"></label>
                <input asp-for="TotalPrice" class="form-control" />
                <span asp-validation-for="TotalPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Whitelists/Index.cshtml
@model IEnumerable<TMDT.Models.Whitelist>

@{
    ViewData["Title"] = "Your Favourist";
}

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewData["Title"]</title>
        <link rel="stylesheet" href="/css/yourfavourist.css" />
    </head>
    <body>
        <div id="main">
            <h1>Your Favourist</h1>
            <div id="products">
                @foreach (var product in Model)
                {
                    <div class="product">
                        <div>
                            <img src="@product.ImagePath" alt="@product.Name" />
                        </div>
                        <div>
                            <h1>@product.Name</h1>
                            <div class="color">
                                Color: @product.Color
                            </div>
                            <div class="Size">
                                Size: @product.Size
                            </div>
                            <div class="price">$@product.TotalPrice</div>
                            @if (product.Number > 0)
                            {
                                <div class="quantity">In Stock: @product.Number</div>
                                <button class="btn add-to-cart" data-id="@product.Id">Add to Cart</button>
                                <a class="btn btn-outline-danger" asp-controller="Whitelists" asp-action="DeleteFavourist" asp-route-id="@product.Id"> Delete </a>
                                <a class="btn btn-outline-danger thongtin" asp-controller="Products" asp-action="Details" asp-route-id="@product.ProductId">
                                    Thong tin
                                </a>
                            }
                            else {
                                <div class="quantity out-of-stock">Out of Stock</div>
                            }
                        </div>
                    </div>
                }
            </div>
        </div>
        <script>
            $('.add-to-cart').on('click', function () {
                var quantity = 1;
                var id = $(this).data('id');
                $.ajax({
                    url: '/Carts/AddToCart/' + id + '?quantity=' + quantity,
                    type: 'GET',
                    success: function (response) {
                        if (response.success === true) {
                            alert('Added to cart successfully');
                        } else {
                            alert(response.message);
                        }
                    },
                    error: function (xhr, status, error) {
                        console.error(error);
                        alert('Failed to add to cart');
                    }
                });
            });
        </script>
    </body>
</html>