Models/Cart.cs
using Microsoft.AspNetCore.Mvc;

namespace TMDT.Models;
public class Cart
{
    public int Id { get; set; }
    public int ProductId { get; set; }
    public string? Name { get; set; }
	public string? ImagePath { get; set; }
    public string? Size { get; set; }
    public string? Color { get; set; }
    public DateTime? TimeOrder { get; set; }
	public int Number {get; set; }
    public float TotalPrice { get; set; }
    public List<PaymentInformationViewModel>? PaymentInformationViewModel { get; set; }
    
}

Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic;
using TMDT.Data;
using TMDT.Models;

namespace TMDT.Controllers
{
    public class CartsController : Controller
    {
        private readonly TMDTDbContext _context;

        public CartsController(TMDTDbContext context)
        {
            _context = context;
        }

        // GET: Carts
        public async Task<IActionResult> Index()
        {
            return View(await _context.Cart.ToListAsync());
        }

        // GET: Carts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _context.Cart
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // GET: Carts/Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpGet]
        public IActionResult AddToCart(int Id, int quantity)
        {
            try
            {
                DateTime dateTime = DateTime.Now;

                var product = _context.Products.FirstOrDefault(q => q.Id == Id);
                var cart = _context.Cart.ToList();
                if (product != null)
                {
                    if (quantity <= 0)
                    {
                        // Nếu số lượng mua là 0 hoặc âm, không thực hiện thêm vào giỏ hàng
                        return BadRequest("Số lượng không hợp lệ");
                    }

                    var existingCartItem = cart.FirstOrDefault(c => c.ProductId == Id);
                    if (existingCartItem != null)
                    {
                        return Json(new { success = false, message = "Sản phẩm đã co trong giỏ hàng" });
                    }

                    var carts = new Cart()
                    {
                        ProductId = product.Id,
                        Number = quantity, // Sử dụng số lượng mua được truyền từ tham số
                        Name = product.Name,
                        TimeOrder = dateTime,
                        Color = product.Color,
                        Size = product.Size,
                        TotalPrice = product.Price * quantity, // Tính tổng giá sản phẩm dựa trên số lượng mua
                        ImagePath = product.ImagePath,
                    };

                    _context.Cart.Add(carts);

                    product.Number -= quantity; // Giảm số lượng sản phẩm còn lại trong kho

                    if (product.Number < 0)
                    {
                        product.Number = 0;
                    }

                    _context.Products.Update(product);
                    _context.SaveChanges();

                    return Json(new { success = true, message = "Sản phẩm đã được thêm vào giỏ hàng" });
                }
                else
                {
                    return NotFound();
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                return StatusCode(500, "Đã xảy ra lỗi khi thêm sản phẩm vào giỏ hàng."); // Trả về mã lỗi 500 và thông báo lỗi
            }
        }

        [HttpPost]
        public IActionResult DeletePaidItems([FromBody] List<int> cartItemIds)
        {
            try
            {
                foreach (var itemId in cartItemIds)
                {
                    var cartItem = _context.Cart.Find(itemId);
                    if (cartItem != null)
                    {
                        _context.Cart.Remove(cartItem);
                    }
                }
                _context.SaveChanges();
                return Ok(new { success = true });
            }
            catch (Exception ex)
            {
                return BadRequest(new { success = false, message = ex.Message });
            }
        }

        /*[HttpGet]
        public IActionResult CheckVoucher(int Id, string voucher)
        {
            var products = _context.Products.FirstOrDefault();
            var cart = _context.Cart.FirstOrDefault(q => q.Id == Id);

            if (products != null && cart != null && cart.DiscountApplied == false && products.VoucherCode == voucher)
            {
                cart.TotalPrice = cart.TotalPrice * (products.decrease / 100);
                cart.DiscountApplied = true;
                _context.Update(cart);
                _context.SaveChanges();
                return Json(new { isValid = true }); // Trả về JSON để xử lý kết quả phía client
            }
            else
            {
                return Json(new { isValid = false }); // Trả về JSON để xử lý kết quả phía client
            }

            
        }
        */


        // GET: Carts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _context.Cart.FindAsync(id);
            if (cart == null)
            {
                return NotFound();
            }
            return View(cart);
        }

        // POST: Carts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id, ProductId, Name, ImagePath,size,color,Number,TotalPrice,DiscountApplied")] Cart cart)
        {
            if (id != cart.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cart);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CartExists(cart.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cart);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Save(int id, int number)
        {
            var cart = await _context.Cart.FindAsync(id);
            var product = await _context.Products.FirstOrDefaultAsync(q => q.Id == cart.ProductId);
            if (cart != null)
            {
                cart.Number = number;
                cart.TotalPrice = number * product.Price;

                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(cart);
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!CartExists(cart.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                }
            }
            else
            {
                return NotFound();
            }
            return View(cart);
        }

        /*[HttpPost] // Change to HttpPost
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int Id, int number)
        {
            var cart = await _context.Cart.FindAsync(Id);
            if (cart == null)
            {
                return NotFound();
            }

            cart.Number = number;

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cart);
                    await _context.SaveChangesAsync();
                    return Json(new { isValid = true });
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CartExists(cart.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return Json(new { isValid = false });
        }*/


        // GET: Carts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await _context.Cart
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // POST: Carts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cart = await _context.Cart.FindAsync(id);
            if (cart != null)
            {
                _context.Cart.Remove(cart);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> DeletebyId(int Id)
        {
            try
            {
                var cartItem = await _context.Cart.ToListAsync();
                var cart = await _context.Cart.FindAsync(Id);
                if (cart != null)

Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TMDT.Data;
using TMDT.Models;

namespace TMDT.Controllers
{
    public class ProductsController : Controller
    {
        private readonly TMDTDbContext _context;

        public ProductsController(TMDTDbContext context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            return View(await _context.Products.ToListAsync());
        }

        [HttpGet]
        public IActionResult GetData(string query)
        {
            if (string.IsNullOrWhiteSpace(query))
            {
                return BadRequest("Query cannot be empty");
            }

            var products = _context.Products
                .Where(p => p.Name.Contains(query))
                .Select(p => new { p.Id, p.Name })
                .ToList();

            return Json(products);
        }

        // GET: Products/Details/5
        public IActionResult Details(int Id)
        {
            var product = _context.Products.FirstOrDefault(p => p.Id == Id);

            if (product == null)
            {
                Console.WriteLine(Id);
                return NotFound(); // Xử lý khi không tìm thấy sản phẩm với ID tương ứng
            }

            return View(product); // Trả về View với sản phẩm tương ứng
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            return View();
        }


        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id, ProductId, Name, Description, ImagePath, Price, Number, decrease, CategoryId,size,color")] Products products)
        {
            if (ModelState.IsValid)
            {
                _context.Add(products);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(products);
        }

        /*public IActionResult InformationSP(int ProductId)
        {
            var product = _context.Products.FirstOrDefault(p => p.ProductId == ProductId);

            if (product == null)
            {
                return NotFound(); // Xử lý khi không tìm thấy sản phẩm với ID tương ứng
            }

            return RedirectToAction(nameof(Details)); // Trả về View với sản phẩm tương ứng
        }*/

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var products = await _context.Products.FindAsync(id);
            if (products == null)
            {
                return NotFound();
            }
            return View(products);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id, ProductId, Name,Description,ImagePath,Price,Number,decrease, CategoryId,size,color")] Products products)
        {
            if (id != products.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(products);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductsExists(products.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(products);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var products = await _context.Products
                .FirstOrDefaultAsync(m => m.Id == id);
            if (products == null)
            {
                return NotFound();
            }

            return View(products);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var products = await _context.Products.FindAsync(id);
            if (products != null)
            {
                _context.Products.Remove(products);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductsExists(int id)
        {
            return _context.Products.Any(e => e.Id == id);
        }
		
		

	}
}

Views/Carts/Create.cshtml
@model TMDT.Models.Cart

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Cart</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                <input asp-for="ImagePath" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalPrice" class="control-label"></label>
                <input asp-for="TotalPrice" class="form-control" />
                <span asp-validation-for="TotalPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Carts/Delete.cshtml
@model TMDT.Models.Cart

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cart</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Number)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Number)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Carts/Details.cshtml
@model TMDT.Models.Cart

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Cart</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Number)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Number)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TimeOrder)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TimeOrder)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Carts/Edit.cshtml
@model TMDT.Models.Cart

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Cart</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                <input asp-for="ImagePath" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalPrice" class="control-label"></label>
                <input asp-for="TotalPrice" class="form-control" />
                <span asp-validation-for="TotalPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Carts/Index.cshtml
@model IEnumerable<TMDT.Models.Cart>

@using Microsoft.AspNetCore.Identity
@using TMDT.Areas.Identity.Data

@inject SignInManager<LOGINUser> SignInManager
@inject UserManager<LOGINUser> UserManager

@{
    ViewData["Title"] =  "Your Carts";
}

<html>
    <head>
        <link rel="stylesheet" href="~/css/cart.css"/>
    </head>
    <body>
    <div id="divall">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        <label for="selectAllCheckbox">
                            <input type="checkbox" id="selectAllCheckbox" />
                            <span>All</span>
                        </label>
                    </th>
                    <th></th>
                    <th> </th>
                    <th></th>
                    <th></th>
                    <th><a asp-controller="Carts" asp-action="DeleteAll" id="deleteall">Xoa tat ca san pham</a></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <input class="checkpr" type="checkbox" />
                        </td>
                        <td>
                            <a style="text-decoration: none;" asp-controller="Products" asp-action="Details" asp-route-id="@item.ProductId">@Html.DisplayFor(modelItem => item.Name)</a>
                        </td>
                        <td>
                            <img style="width: 100px; border-radius: 12px;" src="@Html.DisplayFor(modelItem => item.ImagePath)" />
						</td>
                        <form asp-action="Save" method="post">
                        <td style="width: 100px;">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="@item.Id" name="id" />
                            <input asp-for="@item.Number" class="form-control" name="number" min="0" />
                            <span asp-validation-for="@item.Number" class="text-danger"></span>
                        </td>
                        <td>
                            <div id="itemTotalPrice">@Html.DisplayFor(modelItem => item.TotalPrice) $</div>
                        </td>
                        <td>
                            <input type="submit" value="Save" class="btn btn-primary" />
                            <a asp-controller="Carts" asp-action="DeletebyId" asp-route-Id="@item.Id"><i class="fa-solid fa-trash-alt"></i> </a>
                        </td>
                        </form>
                        
                    </tr>
                }
            </tbody>
		</table>
        <div style="display: flex; justify-content: space-around;">
            <div>
                Price: <span id="price">0</span> $
            </div>
            <div>
                @if (SignInManager.IsSignedIn(User))
                {
                    <button id="payment" type="submit" class="btn btn-outline-danger" style="text-decoration: none; border-radius: 5px; padding: 10px; border: 1px dashed gray; width: 100%; float: right;">Mua Ngay</button>
                }
                else
                {
                    <button id="payment2" type="submit" class="btn btn-outline-danger" style="text-decoration: none; border-radius: 5px; padding: 10px; border: 1px dashed gray; width: 100%; float: right;">Mua Ngay</button>
                }
            </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            /*$('.check-voucher').on('click', function () {
                var voucherInput = $(this).closest('tr').find('.voucher-input');
                var voucher = voucherInput.val();
                var cartId = voucherInput.data('cart-id');
                $.ajax({
                    url: '/Carts/CheckVoucher?Id=' + cartId,
                    method: 'GET',
                    data: { voucher: voucher },
                    success: function (response) {
                        if (response.isValid) {
                            // Cập nhật giá sản phẩm hoặc thực hiện các hành động khác sau khi mã giảm giá hợp lệ
                            alert('Mã giảm giá hợp lệ! Áp dụng thành công!');
                        } else {
                            // Xử lý khi mã giảm giá không hợp lệ
                            alert('Mã giảm giá không hợp lệ hoặc đã hết hạn!');
                        }
                        // Xóa giá trị trong ô nhập liệu
                        voucherInput.val('');
                        location.reload();
                        updateTotalPrice();
                    },
                    error: function () {
                        alert('Đã có lỗi xảy ra trong quá trình xử lý. Vui lòng thử lại sau.');
                    }
                });
            });*/

            $('#selectAllCheckbox').on('change', function () {
                var isChecked = $(this).prop('checked');

                $('.checkpr').prop('checked', isChecked);
                updateTotalPrice();
            });

            // Logic cho từng checkbox cá nhân
            $('.checkpr').on('change', function () {
                var anyUnchecked = $('.checkpr:not(:checked)').length > 0;
                $('#selectAllCheckbox').prop('checked', !anyUnchecked);
                updateTotalPrice();
            });

            function updateTotalPrice() {
                var totalPrice = 0;
                $('.checkpr:checked').each(function () {
                    var price = parseFloat($(this).closest('tr').find('#itemTotalPrice').text());
                    totalPrice += price;
                    return totalPrice;
                });
                $('#price').text(totalPrice.toFixed(2));
            }

            $('#payment').click(function (e) {
                e.preventDefault();

                // Get the selected cart item IDs
                var selectedCartItemIds = $('.checkpr:checked').map(function () {
                    return $(this).closest('tr').find('input[type="hidden"][name="id"]').val();
                }).get();
                console.log(`selectedCartItemIds: ${Array.isArray(selectedCartItemIds) ? 'Array of strings' : typeof selectedCartItemIds}`);

                var totalprice = parseFloat($('#price').text());
                console.log(`totalprice: ${typeof totalprice}`);
                $.ajax({
                    url: '/PaymentInformations/CreateDonhang/',
                    type: 'POST',
                    data: {
                        price: totalprice,
                        cartItemIds: selectedCartItemIds
                    },
                    success: function (response) {
                        if (response.redirectUrl) {
                            /*
                            $.ajax({
                                url: '/Carts/DeletePaidItems' + selectedCartItemIds,
                                type: 'POST',
                                contentType: 'application/json',
                                success: function (deleteResponse) {
                                    window.location.href = response.redirectUrl;
                                },
                                error: function (deleteError) {
                                    alert('Failed to delete paid items from cart. Error: ' + deleteError.responseText);
                                }
                            });
                            */
                            alert('Payment processed successfully.');
                            window.location.href = response.redirectUrl
                        } else {
                            alert('Hay chon san pham!');
                        }
                    },
                    error: function (xhr) {
                        alert('Failed to process payment. Error: ' + xhr.responseText);
                    }
                });
            });
                
            $('#payment2').click(function () { 
                alert('Login to Payment!');
                window.location.href = "/Identity/Account/Login";
            });
        });
	</script>
</body>
</html>